### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by daviwil** [eine/setup-msys2#20]
No issue to report here, just wanted to say thanks for fixing the msys2 update issue that occurred yesterday, it was making me crazy!  The new `install` option also works great.

**Comment by eine** [comment]
Thanks a lot! However, please use this with care. As commented in https://github.com/msys2/MSYS2-packages/issues/1962#issuecomment-630749604, I hope the issue to be fixed upstream. At the same time, MSYS2 will be available by default in the following weeks: actions/virtual-environments#30. Hence, this action might be repurposed soon. Meanwhile, it seems to work!

**Comment by Kha** [comment]
Yes, many thanks from me as well!

**Comment by eine** [comment]
Now that a default MSYS2 installation is available in windows-latest virtual environment, I updated this Action accordingly. Since the default installation is partially updated and includes some pre-installed packages, when `update: true` no additional installation is done. However, when `update: false` a clean installation is done with the latest stable release of MSYS2.

Hence the usage didn't change, and I think that this action is still useful as it provides custom entrypoints for `run` steps.

**Comment by daviwil** [comment]
Yep, this still works fine for me after MSYS2 was included on the Windows image.  Running builds with it every day.  Thanks again!
